---
title: "Data 624 - Project 2"
author: "Baron Curtin"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    toc: true
    theme: cayman
    highlight: github
    df_print: paged
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy = TRUE)
knitr::opts_chunk$set(warning = FALSE)

libs <- c("tidyverse", "readxl", "caret", "mlbench", 'skimr', 'RANN', 'randomForest', 'fastAdaboost', 'gbm', 'xgboost', 'caretEnsemble', 'C50', 'earth', 'DMwR', 'fBasics')

loadPkg <- function(x) {
  if(!require(x, character.only = T)) install.packages(x, dependencies = T, repos = "http://cran.us.r-project.org")
  require(x, character.only = T)
}
lapply(libs, loadPkg)
```


## Load Data
```{r}
# test for blanks
replace_with_na <- function(x, str_to_replace) {
  if(x == str_to_replace && !is.na(x)) {
    return(NA)
  } else {
    return(x)
  }
}

train <- read_xlsx("StudentData.xlsx") %>%
  mutate(`Brand Code` = as.factor(`Brand Code`)) %>%
  mutate_all(replace_with_na, str_to_replace = "") %>%
  drop_na()

test <- read_xlsx("StudentEvaluation- TO PREDICT.xlsx") %>%
  mutate(`Brand Code` = as.factor(`Brand Code`)) %>%
  mutate_all(replace_with_na, str_to_replace = "")

trainX <- train %>%
  select(-PH)
trainY <- train$PH

testX <- test %>%
  select(-PH)
testY <- test$PH

set.seed(7)
```

## Exploratory Analysis
```{r}
glimpse(train)
```


```{r}
summary(train)
```

```{r}
train %>%
  group_by(`Brand Code`) %>%
  summarise(count = n(), percent = count/nrow(train))
```

```{r}
basicStats(select_if(train, is.numeric))[c("nobs", "NAs", "Minimum", "Maximum", "1. Quartile", "3. Quartile", "Mean", "Median", "Variance", "Stdev", "Skewness", "Kurtosis"),]
```



```{r}
library(skimr)
skimmed <- skim_to_wide(train)
skimmed[, c(1:5, 9:11, 13, 15:16)]
```

## Preprocessing
```{r}
# imputation
processMissing <- preProcess(train, method='knnImpute')
processMissing

library(RANN)
trainData <- predict(processMissing, newdata = train)
anyNA(trainData)

summary(trainData)
trainY <- trainData$PH
```

```{r}
# one hot encoding
dummyModel <- dummyVars(PH ~ ., data = trainData)
trainDataDummy <- predict(dummyModel, newdata = trainData)

trainData <- data.frame(trainDataDummy) %>%
  rename_all(str_replace_all, pattern = "X.", replacement = "") %>%
  rename_all(str_replace_all, pattern = "\\.$", replacement = "")

# show structure
str(trainData)
```

```{r}
# re-add PH variable
trainData$PH <- trainY
summary(trainData)
```

## Feature Elimination 
```{r}
subsets <- c(1:5,10,20,30,35)
ctrl <- rfeControl(functions = rfFuncs,
                   method = "repeatedcv",
                   repeats = 5,
                   verbose = FALSE)

lmProfile <- rfe(x=trainData[, 1:35], y=trainData$PH,
                 sizes = subsets,
                 rfeControl = ctrl)

lmProfile
```

```{r}
# best variables for optimal performance
bestVars <- lmProfile$optVariables
```


## Model Fit
```{r, results='hide'}
library(caret)
rf_model <- train(as.formula(paste("PH ~ ", paste(bestVars, collapse = " + "), sep = "")), data=trainData, method='rf')
cubist_model <- train(as.formula(paste("PH ~ ", paste(bestVars, collapse = " + "), sep = "")), data=trainData, method='cubist')
gbm_model <- train(as.formula(paste("PH ~ ", paste(bestVars, collapse = " + "), sep = "")), data=trainData, method='gbm')
nnet_model <- train(as.formula(paste("PH ~ ", paste(bestVars, collapse = " + "), sep = "")), data=trainData, method='nnet')
```

```{r}
# summary of models
summary(rf_model)
```

```{r}
summary(cubist_model)
```


```{r}
summary(gbm_model)
```


```{r}
summary(nnet_model)
```


```{r}
# predictions
rf_predictions <- predict(rf_model)
cubist_predictions <- predict(cubist_model)
gbm_predictions <- predict(gbm_model)
nnet_predictions <- predict(nnet_model)
```

## Test Data Processing
```{r}
# imputation
library(RANN)
testData <- predict(processMissing, newdata = test)

# one hot encoding
testDataDummy <- predict(dummyModel, newdata = testData)
testData <- data.frame(testDataDummy) %>%
  rename_all(str_replace_all, pattern = "X.", replacement = "") %>%
  rename_all(str_replace_all, pattern = "\\.$", replacement = "")

# impute catgorical vars
library(DMwR)
testData <- knnImputation(testData)

```

## Test Data Predictions
```{r}
test_rf_model <- predict(rf_model, testData)
test_cubist_model <- predict(cubist_model, testData)
test_gbm_model <- predict(gbm_model, testData)
test_nnet_model <- predict(nnet_model, testData)
```







